### PR TITLE
move test to dev depedencies

### PR DESCRIPTION
**Pull request by sachaarbonel**
Hi, @JobiJoba just found out that dolphhinsr_dart was slowing down my hot reload `Reloaded 10 of 982 libraries in 643ms.` because it was declared as dependency. This PR is a simple fix, I moved it to dev_depedencies. Tests still pass

### CODE REVIEW

**Comment by JobiJoba** [comment]
Thank you for  that  ^^ sorry for reacting late  I didn't saw any notification :<

**Comment by sachaarbonel** [comment]
Np Np. I've got some other proposals I'll get you updated. Do you want to discuss elsewhere?

**Comment by JobiJoba** [comment]
sure
I'm finally going to use it in one of my project (took time) ^^ so if we can improve it I'm not against

**Comment by JobiJoba** [comment]
I think I'm going to rewrite the  whole library  in a dart way.
When I started the project I never  coded in Dart so I just translate  the javascript  to dart. 
Since then ... I've done a bit more dart ^^

**Comment by sachaarbonel** [comment]
@JobiJoba I'll start from your rewrite then. What I had in mind was to make some changes to be able to see how many cards are scheduled for review over the next week for example, which needs to expose some internals I believe

**Pull request merged**
